name: animatediff_ft
channels:
  - pytorch
  - xformers
dependencies:
  - python=3.10
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.3
  - xformers==0.0.20
  - pip
  - pip:
    - diffusers[torch]
    - transformers==4.25.1
    - imageio==2.27.0
    - gdown
    - einops
    - omegaconf
    - safetensors
    - decord
    - opencv-python
    - scipy
    - ffmpeg-python
    - compel
